# Generated by Django 3.0.5 on 2020-05-01 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_userprofile_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='major',
            new_name='classNum',
        ),
        migrations.AddField(
            model_name='user',
            name='classNum',
            field=models.TextField(null=True),
        ),
    ]
