# Generated by Django 3.0.5 on 2020-05-01 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20200501_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='major',
            field=models.TextField(null=True),
        ),
    ]
