language: python
python:
    - "3.6"
services:
    - docker
install:
    - pip install -r deploy/requirements.txt
    - echo `cat /dev/urandom | head -1 | md5sum | head -c 32` > data/config/secret.key
    - ./init_db.sh
script:
    - docker ps -a
    - docker login --username="$DOCKER_USERNAME" registry.cn-hangzhou.aliyuncs.com --password-stdin
    - docker build -t oj-backend:latest .
    - docker images
notifications:
    slack: onlinejudgeteam:BzBz8UFgmS5crpiblof17K2W