language: python
python:
    - "3.6"
services:
    - docker
install:
    - pip install -r deploy/requirements.txt
    - echo `cat /dev/urandom | head -1 | md5sum | head -c 32` > data/config/secret.key
    - ./init_db.sh
script:
    - docker ps -a
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t oj-backend:latest .
    - docker images
    - docker tag oj-backend:latest registry.cn-hangzhou.aliyuncs.com/oj-just/oj-backend:latest
    - docker push  registry.cn-hangzhou.aliyuncs.com/oj-just/oj-backend:latest
notifications:
    slack: onlinejudgeteam:BzBz8UFgmS5crpiblof17K2W